---
micronaut:
    application:
        name: stock-reserve-mongo

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
    db: "${MONGO_DB:sample}"
    collection: "${MONGO_COLLECTION:stocks}"