apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-sample
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sample
            image: busybox
            command: ["/bin/sh", "-c", "echo `date`"]
          restartPolicy: Never
