apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
spec:
  ports:
  - port: 8080
    nodePort: 30002
  selector:
    app: sampleapp
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deploy
spec:
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: sampleapp:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
